services:
  assurance-conformance:
    build:
      context: .
    network_mode: none
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - assurance-result:/result
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  assurance-result:
