"""Generate the landing visuals for the two next-impact contracts."""

from __future__ import annotations

from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"


def card(x: int, y: int, width: int, title: str, detail: str, accent: str) -> str:
    return f'''<g>
      <rect x="{x}" y="{y}" width="{width}" height="92" rx="16" fill="#101722" stroke="{accent}" stroke-opacity=".55"/>
      <circle cx="{x + 24}" cy="{y + 27}" r="6" fill="{accent}"/>
      <text x="{x + 42}" y="{y + 33}" class="card-title">{escape(title)}</text>
      <text x="{x + 24}" y="{y + 63}" class="card-detail">{escape(detail)}</text>
    </g>'''


def svg(title: str, subtitle: str, kicker: str, cards: tuple[tuple[str, str, str], ...], footer: str) -> str:
    positions = ((52, 214, 360), (460, 214, 360), (868, 214, 360))
    nodes = [card(x, y, width, name, detail, accent) for (x, y, width), (name, detail, accent) in zip(positions, cards)]
    return f'''<!-- Generated by docs/make_next_impact_assets.py -->
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="430" viewBox="0 0 1280 430" role="img" aria-labelledby="title desc">
  <title id="title">{escape(title)}</title><desc id="desc">{escape(subtitle)}</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#07111f"/><stop offset=".55" stop-color="#101024"/><stop offset="1" stop-color="#071517"/></linearGradient>
    <linearGradient id="line" x1="0" x2="1"><stop stop-color="#18b6d9"/><stop offset=".5" stop-color="#a66cff"/><stop offset="1" stop-color="#ffb347"/></linearGradient>
    <filter id="glow"><feGaussianBlur stdDeviation="9"/></filter>
    <marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#7d8fa8"/></marker>
    <style>
      text {{ font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }}
      .kicker {{ fill:#55d7ee; font-size:13px; font-weight:750; letter-spacing:2px; }}
      .headline {{ fill:#f8fbff; font-family:system-ui,-apple-system,"Segoe UI",sans-serif; font-size:38px; font-weight:760; letter-spacing:-1px; }}
      .sub {{ fill:#9fb0c6; font-family:system-ui,-apple-system,"Segoe UI",sans-serif; font-size:17px; }}
      .card-title {{ fill:#f5f8fc; font-size:15px; font-weight:750; }}
      .card-detail {{ fill:#9fb0c6; font-size:12px; }}
      .footer {{ fill:#dbe6f3; font-size:14px; font-weight:650; }}
    </style>
  </defs>
  <rect width="1280" height="430" rx="24" fill="url(#bg)"/>
  <ellipse cx="240" cy="100" rx="240" ry="100" fill="#0aa6c2" opacity=".12" filter="url(#glow)"/>
  <ellipse cx="1050" cy="110" rx="220" ry="110" fill="#a66cff" opacity=".12" filter="url(#glow)"/>
  <text x="52" y="54" class="kicker">{escape(kicker)}</text>
  <text x="52" y="108" class="headline">{escape(title)}</text>
  <text x="52" y="145" class="sub">{escape(subtitle)}</text>
  <path d="M232 195 H1048" stroke="url(#line)" stroke-width="3" opacity=".85"/>
  <path d="M232 195 V212 M640 195 V212 M1048 195 V212" stroke="#7d8fa8" stroke-width="2" marker-end="url(#arrow)"/>
  {''.join(nodes)}
  <rect x="52" y="340" width="1176" height="48" rx="12" fill="#0a0f18" stroke="#26364b"/>
  <text x="640" y="370" text-anchor="middle" class="footer">{escape(footer)}</text>
</svg>
'''


def main() -> None:
    (ASSETS / "rights-continuity.svg").write_text(svg(
        "One case. Several rights. Different clocks.",
        "A timely primary route can still lose the protection that makes review usable.",
        "RIGHTS CONTINUITY CONTRACT / NEW",
        (("MEDICAID + CHIP", "reuse data · preserve coverage", "#18b6d9"), ("HEALTH APPEALS", "urgent ≠ routine sequence", "#a66cff"), ("DISABILITY", "60-day appeal ≠ 15-day election", "#ffb347")),
        "EXACT = right set ∧ trigger ∧ clock ∧ minimum evidence ∧ channel ∧ owner ∧ receipt",
    ))
    (ASSETS / "critical-event-fanout.svg").write_text(svg(
        "Response succeeds. Obligations stay open.",
        "Critical events fan out into independently owned reports, recipients, updates, and receipts.",
        "CRITICAL EVENT FAN-OUT / NEW",
        (("PIPELINE", "contain · 1-hour call · 48-hour update", "#ff7b42"), ("HEALTH DATA", "actor · people · HHS · media", "#a66cff"), ("CLINICAL TRIAL", "7-day · 15-day · follow-up", "#52d6a6")),
        "EXACT = response ∧ complete graph ∧ actor ∧ clock ∧ recipient ∧ owner ∧ executed receipt",
    ))
    print("wrote rights-continuity.svg and critical-event-fanout.svg")


if __name__ == "__main__":
    main()
