#!/usr/bin/env python3
"""Build the browser-local Federal Pilot Desk from canonical exchange artifacts."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KIT = ROOT / "federal-pilot-kit"
DOCS = ROOT / "docs"
OUTPUT = DOCS / "federal-pilot-data.json"
ASSET = DOCS / "assets" / "federal-pilot.svg"
SCHEMA_OUTPUTS = {
    "agency-intake.schema.json": DOCS / "federal-pilot-agency.schema.json",
    "vendor-evidence-response.schema.json": DOCS / "federal-pilot-vendor.schema.json",
    "acceptance-test-manifest.schema.json": DOCS / "federal-pilot-tests.schema.json",
}


def load_module():
    spec = importlib.util.spec_from_file_location("aau_pilot", KIT / "aau_pilot.py")
    if not spec or not spec.loader:
        raise RuntimeError("cannot load federal-pilot-kit/aau_pilot.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render_svg(pilots: int, requirements: int, cases: int, visible_gaps: int) -> str:
    return f'''<!-- Generated by docs/make_federal_pilot_data.py -->
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="560" viewBox="0 0 1280 560" role="img" aria-labelledby="title desc">
  <title id="title">AAU Federal Pilot Kit</title>
  <desc id="desc">A forkable agency, responder, and reviewer evidence exchange with public synthetic pilots, exact tests, visible gaps, and protected human authority.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#071112"/><stop offset=".52" stop-color="#0a2523"/><stop offset="1" stop-color="#08151c"/></linearGradient>
    <linearGradient id="line" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#39e6ad"/><stop offset=".52" stop-color="#ffd166"/><stop offset="1" stop-color="#7ebcff"/></linearGradient>
    <pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#8fffe0" stroke-opacity=".055"/></pattern>
    <filter id="glow"><feGaussianBlur stdDeviation="7" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
    <style>text{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}}.sans{{font-family:system-ui,-apple-system,Segoe UI,sans-serif}}.k{{font-size:12px;font-weight:800;letter-spacing:2px}}.h{{font-size:42px;font-weight:850;letter-spacing:-1.8px}}.sub{{font-size:16px;fill:#b8cfca}}.node{{font-size:11px;font-weight:900;letter-spacing:1px}}.num{{font-size:28px;font-weight:900}}.label{{font-size:10px;font-weight:800;letter-spacing:1px}}</style>
  </defs>
  <rect width="1280" height="560" rx="25" fill="url(#bg)"/><rect width="1280" height="560" rx="25" fill="url(#grid)"/>
  <path d="M0 3H1280" stroke="url(#line)" stroke-width="6"/>
  <text x="58" y="59" class="k" fill="#66efc0">AAU / FEDERAL PILOT KIT 0.3 / FORK THE MISSION · VERIFY THE EVIDENCE</text>
  <text x="58" y="119" class="h sans" fill="#f4fff9">Claims enter.</text><text x="58" y="168" class="h sans" fill="#ffd166">Gaps stay visible.</text>
  <text x="58" y="205" class="sub sans">One open handoff for agency outcomes, responder evidence, exact tests, and accountable review.</text>
  <g transform="translate(876 36)"><path d="M48 80h230v128H48z" fill="#071b1b" stroke="#39e6ad" stroke-width="2"/><path d="M72 109h92M72 134h164M72 159h130" stroke="#7bdabe" stroke-width="7" stroke-linecap="round" opacity=".62"/><path d="M197 91l67 67-67 67" fill="#0b2527" stroke="#ffd166" stroke-width="3" filter="url(#glow)"/><path d="M213 155l15 15 28-35" fill="none" stroke="#ffd166" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><text x="163" y="248" text-anchor="middle" class="k" fill="#7ebcff">NON-RANKING / LOCAL / INSPECTABLE</text></g>
  <path d="M82 330H1195" stroke="#285953" stroke-width="3"/><path d="M82 330H1125" stroke="url(#line)" stroke-width="6" stroke-linecap="round"/>
  <g class="node" text-anchor="middle">
    <g transform="translate(100 330)"><circle r="25" fill="#39e6ad"/><text y="4" fill="#071814">01</text><text y="61" fill="#69edc4">AGENCY</text></g>
    <g transform="translate(370 330)"><circle r="25" fill="#70dfbb"/><text y="4" fill="#071814">02</text><text y="61" fill="#8de8cd">RESPONDER</text></g>
    <g transform="translate(640 330)"><circle r="25" fill="#ffd166"/><text y="4" fill="#15130a">03</text><text y="61" fill="#ffd166">EXACT TEST</text></g>
    <g transform="translate(910 330)"><circle r="25" fill="#91c5ff"/><text y="4" fill="#07111c">04</text><text y="61" fill="#91c5ff">REVIEWER</text></g>
    <g transform="translate(1180 330)"><circle r="25" fill="#7ebcff"/><text y="4" fill="#07111c">05</text><text y="61" fill="#7ebcff">HUMAN</text></g>
  </g>
  <g transform="translate(58 436)"><rect width="1164" height="82" rx="13" fill="#041314" stroke="#2b5b55"/>
    <g text-anchor="middle"><text x="145" y="37" class="num" fill="#39e6ad">{pilots}</text><text x="145" y="61" class="label" fill="#9dbbb5">REFERENCE PILOTS</text>
    <text x="436" y="37" class="num" fill="#ffd166">{requirements}</text><text x="436" y="61" class="label" fill="#9dbbb5">MEASURABLE GATES</text>
    <text x="727" y="37" class="num" fill="#7ebcff">{cases}</text><text x="727" y="61" class="label" fill="#9dbbb5">SYNTHETIC CASES</text>
    <text x="1018" y="37" class="num" fill="#ff8c7e">{visible_gaps}</text><text x="1018" y="61" class="label" fill="#9dbbb5">VISIBLE GAPS</text></g></g>
</svg>'''


def main() -> None:
    module = load_module()
    examples = []
    requirement_count = 0
    case_count = 0
    visible_gaps = 0
    for directory in sorted((KIT / "examples").iterdir()):
        agency = json.loads((directory / "agency-intake.json").read_text())
        vendor = json.loads((directory / "vendor-response.json").read_text())
        tests = json.loads((directory / "acceptance-tests.json").read_text())
        assessment = module.assess_exchange(agency, vendor, tests)
        examples.append(
            {
                "slug": directory.name,
                "agency": agency,
                "vendor": vendor,
                "tests": tests,
                "assessment": assessment,
                "paths": {
                    "agency": f"federal-pilot-kit/examples/{directory.name}/agency-intake.json",
                    "vendor": f"federal-pilot-kit/examples/{directory.name}/vendor-response.json",
                    "tests": f"federal-pilot-kit/examples/{directory.name}/acceptance-tests.json",
                },
            }
        )
        requirement_count += assessment["summary"]["requirements"]
        case_count += assessment["summary"]["cases"]
        visible_gaps += assessment["summary"]["visible_gaps"]
    review_prompts = json.loads((KIT / "acquisition-review-prompts.json").read_text())
    output = {
        "version": "aau-federal-pilot-desk/0.3",
        "privacy": "Files stay in this browser tab. The Pilot Desk does not upload, persist, or transmit them.",
        "boundary": "No vendor ranking, award recommendation, certification, compliance finding, or government approval is produced.",
        "schema_paths": {
            "agency": "federal-pilot-agency.schema.json",
            "vendor": "federal-pilot-vendor.schema.json",
            "tests": "federal-pilot-tests.schema.json",
        },
        "pack_files": list(module.PACK_NAMES),
        "review_prompts": review_prompts,
        "examples": examples,
    }
    OUTPUT.write_text(json.dumps(output, indent=2) + "\n")
    for source, destination in SCHEMA_OUTPUTS.items():
        destination.write_text((KIT / source).read_text())
    ASSET.write_text(
        render_svg(len(examples), requirement_count, case_count, visible_gaps)
    )
    print(
        "wrote Federal Pilot Desk data — "
        f"{len(examples)} pilots, {requirement_count} gates, {case_count} cases, "
        f"{visible_gaps} visible gaps"
    )


if __name__ == "__main__":
    main()
