"""Generate the matched seven-industry Public Protection report."""

from __future__ import annotations

import json
from pathlib import Path

from make_decision_gate_report import (
    aggregate_table,
    exact_matrix,
    load_results,
    miss_sample,
    provider_label,
)

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs" / "use-cases.json"
OUTPUT = ROOT / "PUBLIC_PROTECTION_REPORT.md"


def cases() -> list[dict]:
    catalog = json.loads(CATALOG.read_text())
    return [item for item in catalog if item["kind"] == "public-protection benchmark"]


def render() -> str:
    items = cases()
    all_results = {item["path"]: load_results(item) for item in items}
    providers = sorted(
        {
            provider_label(result)
            for results in all_results.values()
            for result in results
            if result["backend"] != "mock"
        }
    )
    assert len(items) == 7, f"expected the matched 7-lab wave, found {len(items)}"
    assert len(providers) == 2, f"expected two clean real providers, found {providers}"
    for item in items:
        results = all_results[item["path"]]
        mocks = [result for result in results if result["backend"] == "mock"]
        reals = {provider_label(result) for result in results if result["backend"] != "mock"}
        assert len(mocks) == 1, f"{item['path']} must contain one deterministic baseline"
        assert reals == set(providers), (
            f"{item['path']} has incomplete clean provider evidence: expected "
            f"{providers}, found {sorted(reals)}"
        )
    provider_summary = ", ".join(f"`{provider}`" for provider in providers)
    return f"""# Public Protection — matched industry report

**7 industries · 224 committed scenarios · 8 balanced archetypes per lab · 3 repeats
per benchmark arm.**

This wave introduces the [Protection Receipt Contract](PROTECTION_RECEIPT_CONTRACT.md):
an action is not credited until the exact subject, current rule, complete gates, live
clock/channel, protected owner, and truthful executed receipt remain joined. It uses the
same [Decision Gate Contract](DECISION_GATE_CONTRACT.md) scorecard, so its results stay
comparable with the wider repository. Current committed real providers: {provider_summary}.

These are synthetic smoke suites, not production rankings, legal conclusions, emergency
instructions, safety certifications, regulatory filings, or claims about live systems.

## Exact decision matrix

{exact_matrix(items, all_results, providers)}

## What the exact score contains

{aggregate_table(items, all_results, providers)}

Means are calculated across seven lab-level means. Confidence intervals remain in each
lab's committed result Markdown; provider p50 includes collection-time network conditions.

## One reproducible miss per industry

{miss_sample(items, all_results)}

The matched traps deliberately cross different public systems while retaining the same
failure anatomy:

- similarity replaces exact identity or path classification;
- one missing gate disappears under urgency or operational truth;
- a draft, intake, appointment, correction, dispute, or attempt becomes a false completion;
- the agent crosses into a protected repair, payment, filing, certification, or legal state.

Open a linked lab and inspect `results/*.json` for the gold contract, predicted record,
executed tool trace, usage, and provider provenance. Provider errors are excluded and make
this generator fail the completeness assertion.

## Use the wave

1. Start with the nearest protection/receipt confusion in your own workflow.
2. Reproduce the deterministic miss at $0.
3. Replay identical cases across a model or tool-layer intervention.
4. Inspect subject, rule, gate, clock, authority, and receipt fidelity separately.
5. Replace the fictional snapshot only with an accountable domain owner.

<sub>Generated by `docs/make_public_protection_report.py` from committed catalog and result
JSON. Edit the labs or their evidence; do not hand-edit this report.</sub>
"""


def main() -> None:
    OUTPUT.write_text(render())
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
