"""Generate the matched seven-industry Regulatory Clock Collision report."""

from __future__ import annotations

import json
from pathlib import Path

from make_decision_gate_report import (
    aggregate_table,
    exact_matrix,
    load_results,
    miss_sample,
    provider_label,
)

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs" / "use-cases.json"
OUTPUT = ROOT / "CLOCK_COLLISION_REPORT.md"


def cases() -> list[dict]:
    catalog = json.loads(CATALOG.read_text())
    return [item for item in catalog if item["kind"] == "clock-collision benchmark"]


def render() -> str:
    items = cases()
    all_results = {item["path"]: load_results(item) for item in items}
    providers = sorted(
        {
            provider_label(result)
            for results in all_results.values()
            for result in results
            if result["backend"] != "mock"
        }
    )
    assert len(items) == 7, f"expected 7 clock-collision labs, found {len(items)}"
    assert len(providers) == 2, f"expected two clean real providers, found {providers}"
    for item in items:
        results = all_results[item["path"]]
        mocks = [result for result in results if result["backend"] == "mock"]
        reals = {provider_label(result) for result in results if result["backend"] != "mock"}
        assert len(mocks) == 1, f"{item['path']} must contain one deterministic baseline"
        assert reals == set(providers), (
            f"{item['path']} has incomplete provider evidence: expected {providers}, "
            f"found {sorted(reals)}"
        )
    provider_summary = ", ".join(f"`{provider}`" for provider in providers)
    return f"""# Regulatory Clock Collision — matched industry report

**7 industries · 224 committed scenarios · 8 balanced archetypes per lab · 3 repeats
per benchmark arm.**

This wave introduces the [Obligation Graph Contract](OBLIGATION_GRAPH_CONTRACT.md): an
event is not handled exactly until every applicable obligation, clock origin, deadline,
recipient/channel, protected owner, and executed receipt remains joined. It reuses the
[Decision Gate Contract](DECISION_GATE_CONTRACT.md) scorecard so results remain comparable.
Current committed real providers: {provider_summary}.

These are synthetic smoke suites—not production rankings, legal conclusions, medical or
housing advice, securities filings, nuclear classifications, or claims about live systems.

## Exact decision matrix

{exact_matrix(items, all_results, providers)}

## What the exact score contains

{aggregate_table(items, all_results, providers)}

Means are calculated across seven lab-level means. Confidence intervals remain in each
lab's result Markdown; provider p50 includes collection-time network conditions.

## One reproducible miss per industry

{miss_sample(items, all_results)}

The matched traps retain one failure anatomy while changing the regulated system:

- one event is mistaken for one obligation instead of a graph;
- a nearby actor, threshold, or exception overwrites the exact rule;
- discovery, occurrence, receipt, or a calendar approximation starts the wrong clock;
- a draft, notice, initiation, call attempt, or review becomes a false later stage;
- the agent crosses into medical, materiality, eligibility, appeal, emergency, or filing authority.

Open a linked lab and inspect `results/*.json` for gold contracts, predicted records,
executed tool traces, usage, and provider provenance. Provider errors are excluded and
make this generator fail the completeness assertion.

## Use the wave

1. Model one real event as a set of independently triggered obligations.
2. Give every node a versioned rule, clock origin, due time, recipient, owner, and receipt.
3. Add a clean twin where one fact changes one node or deadline.
4. Remove protected decisions and irreversible actions from the model's tools.
5. Replay identical scenarios after every model, rule, prompt, or tool change.

<sub>Generated by `docs/make_clock_collision_report.py` from committed catalog and result
JSON. Edit the labs or evidence; do not hand-edit this report.</sub>
"""


def main() -> None:
    OUTPUT.write_text(render())
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
