"""Generate the matched three-industry Proof Before Action report."""

from __future__ import annotations

import json
from pathlib import Path

from make_decision_gate_report import (
    aggregate_table,
    exact_matrix,
    load_results,
    miss_sample,
    provider_label,
)

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs" / "use-cases.json"
OUTPUT = ROOT / "PROOF_ACTION_REPORT.md"


def cases() -> list[dict]:
    catalog = json.loads(CATALOG.read_text())
    return [item for item in catalog if item["kind"] == "proof-before-action benchmark"]


def render() -> str:
    items = cases()
    all_results = {item["path"]: load_results(item) for item in items}
    providers = sorted(
        {
            provider_label(result)
            for results in all_results.values()
            for result in results
            if result["backend"] != "mock"
        }
    )
    assert len(items) == 3, f"expected the matched 3-lab wave, found {len(items)}"
    assert len(providers) == 2, f"expected two clean real providers, found {providers}"
    for item in items:
        results = all_results[item["path"]]
        mocks = [result for result in results if result["backend"] == "mock"]
        reals = {provider_label(result) for result in results if result["backend"] != "mock"}
        assert len(mocks) == 1, f"{item['path']} must contain one deterministic baseline"
        assert reals == set(providers), (
            f"{item['path']} has incomplete clean provider evidence: expected "
            f"{providers}, found {sorted(reals)}"
        )
    provider_summary = ", ".join(f"`{provider}`" for provider in providers)
    return f"""# Proof Before Action — matched industry report

**3 industries · 32 committed scenarios per lab · 8 balanced archetypes · 3 repeats
per benchmark arm.**

This wave extends the [Decision Gate Contract](DECISION_GATE_CONTRACT.md) into everyday work
where an apparently helpful action can outrun its proof: publishing a cited claim, booking a
household service visit, or certifying a grant packet. Current committed real providers:
{provider_summary}.

These are synthetic smoke suites, not production rankings, emergency instructions, grant
advice, or truth certifications. The first eight seeded scenarios are repeated to expose
every archetype with bounded cost; the full 32-scenario worlds are committed.

## Exact decision matrix

{exact_matrix(items, all_results, providers)}

## What the exact score contains

{aggregate_table(items, all_results, providers)}

Means are calculated across three lab-level means. Confidence intervals remain in each
lab's committed result Markdown; provider p50 includes collection-time network conditions.

## One reproducible miss per industry

{miss_sample(items, all_results)}

The matched transfer traps are deliberately different in content but identical in shape:

- a real source is relevant but does not entail the drafted claim;
- a routine no-heat workflow becomes unsafe when gas or CO danger appears;
- an accepted prior-award packet omits a current-award obligation.

Open a linked lab and inspect `results/*.json` for the exact gold contract, predicted
record, executed tool trace, usage, and provider provenance. Provider errors are excluded
and make this generator fail the completeness assertion.

## Use the wave

1. Start with the nearest proof-transfer failure, not merely the nearest industry.
2. Reproduce the deterministic miss at $0.
3. Replay the same scenario across models or a tool-layer intervention.
4. Inspect evidence and gate fidelity before aggregate accuracy.
5. Replace the fictional policy only with an accountable domain owner.

<sub>Generated by `docs/make_proof_action_report.py` from committed catalog and result JSON.
Edit the labs or their evidence; do not hand-edit this report.</sub>
"""


def main() -> None:
    OUTPUT.write_text(render())
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
