#!/usr/bin/env python3
"""Generate the public Federal AI Portfolio Observatory from canonical contracts."""

from __future__ import annotations

import importlib.util
import json
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OBSERVATORY = ROOT / "federal-portfolio-observatory"
DOCS = ROOT / "docs"
EXAMPLES = OBSERVATORY / "examples"
OUTPUT = DOCS / "federal-portfolio-data.json"
ASSET = DOCS / "assets" / "federal-portfolio.svg"
SCHEMAS = {
    "inventory.schema.json": "federal-ai-portfolio.schema.json",
    "public-value-ledger.schema.json": "public-value-ledger.schema.json",
    "three-layer-tev-v.schema.json": "three-layer-tev-v.schema.json",
    "clause-testbench.schema.json": "clause-testbench.schema.json",
}


def load_module():
    spec = importlib.util.spec_from_file_location(
        "aau_portfolio", OBSERVATORY / "aau_portfolio.py"
    )
    if not spec or not spec.loader:
        raise RuntimeError("cannot load federal-portfolio-observatory/aau_portfolio.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render_svg(summary: dict, measured: int, layers: int, clauses: int) -> str:
    return f'''<!-- Generated by docs/make_federal_portfolio_data.py -->
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="560" viewBox="0 0 1280 560" role="img" aria-labelledby="title desc">
  <title id="title">AAU Federal AI Portfolio Observatory</title>
  <desc id="desc">A browser-local portfolio evidence desk showing documented investments, open evidence gaps, bounded measurements, three testing layers, and testable acquisition obligations.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#07131f"/><stop offset=".5" stop-color="#10233d"/><stop offset="1" stop-color="#13101f"/></linearGradient>
    <linearGradient id="signal"><stop stop-color="#65e6ff"/><stop offset=".52" stop-color="#baf36a"/><stop offset="1" stop-color="#ffce66"/></linearGradient>
    <pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#65e6ff" stroke-opacity=".055"/></pattern>
    <style>text{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}}.sans{{font-family:system-ui,-apple-system,Segoe UI,sans-serif}}.k{{font-size:12px;font-weight:850;letter-spacing:2px}}.h{{font-size:42px;font-weight:900;letter-spacing:-1.8px}}.sub{{font-size:16px;fill:#b7c7dc}}.num{{font-size:29px;font-weight:950}}.label{{font-size:10px;font-weight:850;letter-spacing:1px}}.node{{font-size:11px;font-weight:900;letter-spacing:1px}}</style>
  </defs>
  <rect width="1280" height="560" rx="25" fill="url(#bg)"/><rect width="1280" height="560" rx="25" fill="url(#grid)"/><path d="M0 3H1280" stroke="url(#signal)" stroke-width="6"/>
  <text x="58" y="59" class="k" fill="#65e6ff">AAU / FEDERAL AI PORTFOLIO OBSERVATORY 0.5 / PUBLIC + SYNTHETIC ONLY</text>
  <text x="58" y="119" class="h sans" fill="#f7fbff">See the portfolio.</text><text x="58" y="168" class="h sans" fill="#baf36a">Interrogate the evidence.</text>
  <text x="58" y="205" class="sub sans">Quality gaps, possible overlap, public value, TEV&amp;V, clauses, and dated policy—without ranking investments.</text>
  <g transform="translate(895 43)"><circle cx="122" cy="105" r="99" fill="#081725" stroke="#65e6ff" stroke-width="2"/><circle cx="122" cy="105" r="69" fill="none" stroke="#baf36a" stroke-dasharray="6 8"/><path d="M64 151L180 58M77 72h56M112 138h61" stroke="#ffce66" stroke-width="9" stroke-linecap="round"/><circle cx="87" cy="127" r="11" fill="#65e6ff"/><circle cx="157" cy="84" r="11" fill="#baf36a"/><text x="122" y="230" text-anchor="middle" class="k" fill="#93c8ff">LOCAL · NON-RANKING · INSPECTABLE</text></g>
  <path d="M82 330H1195" stroke="#31506f" stroke-width="3"/><path d="M82 330H1128" stroke="url(#signal)" stroke-width="6" stroke-linecap="round"/>
  <g class="node" text-anchor="middle"><g transform="translate(110 330)"><circle r="25" fill="#65e6ff"/><text y="4" fill="#07131f">01</text><text y="61" fill="#65e6ff">INVENTORY</text></g><g transform="translate(375 330)"><circle r="25" fill="#8eeccc"/><text y="4" fill="#07131f">02</text><text y="61" fill="#8eeccc">QUALITY</text></g><g transform="translate(640 330)"><circle r="25" fill="#baf36a"/><text y="4" fill="#10190a">03</text><text y="61" fill="#baf36a">PUBLIC VALUE</text></g><g transform="translate(905 330)"><circle r="25" fill="#ffce66"/><text y="4" fill="#1d1200">04</text><text y="61" fill="#ffce66">TEST</text></g><g transform="translate(1170 330)"><circle r="25" fill="#93c8ff"/><text y="4" fill="#07131f">05</text><text y="61" fill="#93c8ff">HUMAN DECISION</text></g></g>
  <g transform="translate(58 436)"><rect width="1164" height="82" rx="13" fill="#06111d" stroke="#31506f"/><g text-anchor="middle"><text x="116" y="37" class="num" fill="#65e6ff">{summary['use_cases']}</text><text x="116" y="61" class="label" fill="#9fb0c5">SYNTHETIC ENTRIES</text><text x="349" y="37" class="num" fill="#baf36a">{summary['documented']}</text><text x="349" y="61" class="label" fill="#9fb0c5">DOCUMENTED</text><text x="582" y="37" class="num" fill="#ff8f82">{summary['critical_gaps']}</text><text x="582" y="61" class="label" fill="#9fb0c5">CRITICAL GAPS</text><text x="815" y="37" class="num" fill="#ffce66">{measured}</text><text x="815" y="61" class="label" fill="#9fb0c5">BOUNDED MEASUREMENT</text><text x="1048" y="37" class="num" fill="#93c8ff">{layers}+{clauses}</text><text x="1048" y="61" class="label" fill="#9fb0c5">TEST LAYERS + CLAUSES</text></g></g>
</svg>'''


def main() -> None:
    module = load_module()
    inventory = json.loads((EXAMPLES / "synthetic-agency-inventory.json").read_text())
    ledger = json.loads((EXAMPLES / "public-value-ledger.json").read_text())
    tevv = json.loads((EXAMPLES / "three-layer-tev-v-plan.json").read_text())
    clauses = json.loads((EXAMPLES / "clause-testbench.json").read_text())
    sources = json.loads((OBSERVATORY / "sources.json").read_text())
    catalog = json.loads((DOCS / "use-cases.json").read_text())

    module.validate_inventory(inventory)
    module.validate_public_value(ledger, inventory)
    module.validate_tev_v(tevv, inventory)
    module.validate_clauses(clauses)
    module.validate_sources(sources)
    analysis = module.analyze_inventory(inventory, catalog)
    value = module.assess_public_value(ledger, inventory)
    coverage = module.tevv_coverage(tevv, inventory)
    clause_coverage = module.clause_coverage(clauses)
    scan = module.scan_sensitive(inventory, ledger, tevv, clauses)
    as_of = date.fromisoformat(max(item["last_verified"] for item in sources["sources"]))
    drift = module.policy_drift(sources, as_of)
    if scan["finding_count"]:
        raise ValueError("canonical public examples failed the narrow sensitive scan")

    output = {
        "version": "aau-federal-portfolio-observatory/0.5",
        "privacy": "Local inventory files stay in this browser tab and are never uploaded, stored, or transmitted.",
        "boundary": analysis["boundary"],
        "schema_paths": {key.removesuffix(".schema.json"): value for key, value in SCHEMAS.items()},
        "inventory": inventory,
        "analysis": analysis,
        "public_value": {"ledger": ledger, "assessment": value},
        "tev_v": {"plan": tevv, "coverage": coverage},
        "clauses": {"library": clauses, "coverage": clause_coverage},
        "sources": sources,
        "policy_drift": drift,
        "privacy_scan": scan,
    }
    OUTPUT.write_text(json.dumps(output, indent=2) + "\n")
    for source_name, destination_name in SCHEMAS.items():
        (DOCS / destination_name).write_text((OBSERVATORY / source_name).read_text())
    ASSET.write_text(
        render_svg(
            analysis["summary"],
            value["summary"]["measured"],
            len(coverage["layers"]),
            clause_coverage["areas"],
        )
    )
    print(
        "wrote Federal Portfolio Observatory — "
        f"{analysis['summary']['use_cases']} entries, "
        f"{analysis['summary']['critical_gaps']} critical gaps, "
        f"{len(coverage['layers'])} TEV&V layers, {clause_coverage['areas']} clause areas"
    )


if __name__ == "__main__":
    main()
