"""Generate the landing-page hero with proof points derived from repository data.

The detailed backdrop is intentionally static artwork. The proof strip is SVG text
generated from source-of-truth files, so adding a use case or evaluation never
requires opening an image editor:

    python docs/make_hero.py
"""

from __future__ import annotations

import base64
import json
import re
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"
CATALOG = ROOT / "docs" / "use-cases.json"
TAXONOMY = ASSETS / "taxonomy.json"
BACKDROP = ASSETS / "hero-v4.webp"
OUTPUT = ASSETS / "hero.svg"
STATS_LIGHT = ASSETS / "stats-light.svg"
STATS_DARK = ASSETS / "stats-dark.svg"


def repository_stats() -> tuple[tuple[str, int, str], ...]:
    """Return label, value, and accent for every public proof point."""
    cases = json.loads(CATALOG.read_text())
    taxonomy = json.loads(TAXONOMY.read_text())
    model_evals = sum(
        json.loads(path.read_text()).get("backend") != "mock"
        for path in ROOT.glob("*/*/results/eval_*.json")
    )
    return (
        ("VERIFIED USE CASES", len(cases), "#1687ff"),
        ("INDUSTRIES", len({item["industry"] for item in cases}), "#23d65b"),
        ("MODEL EVALS", model_evals, "#a865ff"),
        ("OBSERVED FAILURES", taxonomy["failure_modes"], "#ff4938"),
    )


def render(stats: tuple[tuple[str, int, str], ...]) -> str:
    encoded_backdrop = base64.b64encode(BACKDROP.read_bytes()).decode("ascii")
    proof = " · ".join(f"{value} {label.lower()}" for label, value, _accent in stats)
    columns: list[str] = []
    start_x, column_width = 88, 168
    for index, (label, value, accent) in enumerate(stats):
        x = start_x + index * column_width
        if index:
            columns.append(
                f'<path d="M {x - 18} 804 V 861" stroke="#31363e" stroke-width="1"/>'
            )
        columns.extend(
            (
                f'<circle cx="{x}" cy="816" r="4" fill="{accent}"/>',
                f'<text x="{x + 14}" y="828" class="proof-value" fill="#f5f7fa">{value}</text>',
                f'<text x="{x}" y="856" class="proof-label" fill="{accent}">{escape(label)}</text>',
            )
        )

    return f'''<!-- Generated by docs/make_hero.py; edit the data, not the numbers. -->
<svg xmlns="http://www.w3.org/2000/svg" width="1672" height="941" viewBox="0 0 1672 941" role="img" aria-labelledby="hero-title hero-description">
  <title id="hero-title">Awesome Agentic Use Cases — verified, not just runnable</title>
  <desc id="hero-description">Evidence paths through tools, policy gates, uncertainty, and failures. Repository proof points: {escape(proof)}.</desc>
  <defs>
    <linearGradient id="proof-surface" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#050607"/>
      <stop offset="0.7" stop-color="#080a0d"/>
      <stop offset="1" stop-color="#080a0d" stop-opacity="0.96"/>
    </linearGradient>
    <filter id="proof-glow" x="-20%" y="-50%" width="140%" height="200%">
      <feGaussianBlur stdDeviation="7"/>
    </filter>
    <style>
      text {{ font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace; }}
      .proof-value {{ font-size: 34px; font-weight: 750; letter-spacing: -1px; }}
      .proof-label {{ font-size: 12px; font-weight: 700; letter-spacing: 1.25px; }}
    </style>
  </defs>
  <image width="1672" height="941" href="data:image/webp;base64,{encoded_backdrop}"/>
  <rect x="68" y="783" width="704" height="96" rx="8" fill="#050607" opacity="0.96" filter="url(#proof-glow)"/>
  <rect x="68" y="783" width="704" height="96" rx="8" fill="url(#proof-surface)" stroke="#29303a"/>
  <path d="M 69 784 H 771" stroke="#1687ff" stroke-width="2" opacity="0.75"/>
  {''.join(columns)}
</svg>
'''


def render_stats(stats: tuple[tuple[str, int, str], ...], *, dark: bool) -> str:
    values = {label: value for label, value, _accent in stats}
    industries = values["INDUSTRIES"]
    model_evals = values["MODEL EVALS"]
    failures = values["OBSERVED FAILURES"]
    surface = "#1a1a19" if dark else "#fcfcfb"
    stroke = "rgba(255,255,255,0.10)" if dark else "rgba(11,11,11,0.10)"
    dividers = "#2c2c2a" if dark else "#e1e0d9"
    foreground = "#ffffff" if dark else "#0b0b0b"
    proof = (
        f"{industries} industries shipping, {model_evals} verified model-evals, "
        f"{failures} failure modes observed, at least 3 repeats per scenario, "
        "$0 to reproduce on free tiers"
    )
    return f'''<!-- Generated by docs/make_hero.py; edit source data, not these numbers. -->
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="128" viewBox="0 0 1280 128" role="img" aria-label="{escape(proof)}">
  <rect x="1" y="1" width="1278" height="126" rx="14" fill="{surface}" stroke="{stroke}"/>
  <g stroke="{dividers}"><path d="M 256 24 V 104"/><path d="M 512 24 V 104"/><path d="M 768 24 V 104"/><path d="M 1024 24 V 104"/></g>
  <g font-family="system-ui, -apple-system, 'Segoe UI', sans-serif" text-anchor="middle">
    <g fill="{foreground}" font-size="34" font-weight="700">
      <text x="128" y="66">{industries}</text>
      <text x="384" y="66">{model_evals}</text>
      <text x="640" y="66">{failures}</text>
      <text x="896" y="66">n≥3</text>
      <text x="1152" y="66">$0</text>
    </g>
    <g fill="#898781" font-size="15">
      <text x="128" y="94">industries shipping</text>
      <text x="384" y="94">verified model-evals</text>
      <text x="640" y="94">failure modes observed</text>
      <text x="896" y="94">repeats per scenario</text>
      <text x="1152" y="94">to reproduce (free tiers)</text>
    </g>
  </g>
</svg>
'''


def replace_once(text: str, pattern: str, replacement: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text)
    if count != 1:
        raise ValueError(f"expected exactly one {label}, found {count}")
    return updated


def sync_public_copy(stats: tuple[tuple[str, int, str], ...]) -> None:
    values = {label: value for label, value, _accent in stats}
    cases = values["VERIFIED USE CASES"]
    industries = values["INDUSTRIES"]
    model_evals = values["MODEL EVALS"]
    failures = values["OBSERVED FAILURES"]
    patterns = json.loads(TAXONOMY.read_text())["patterns"]

    readme_path = ROOT / "README.md"
    readme = readme_path.read_text()
    readme = replace_once(
        readme,
        r'<img alt="\d+ industries shipping, \d+ verified model-evals, \d+ failure modes observed, at least 3 repeats per scenario, \$0 to reproduce on free tiers"',
        f'<img alt="{industries} industries shipping, {model_evals} verified model-evals, {failures} failure modes observed, at least 3 repeats per scenario, $0 to reproduce on free tiers"',
        "README proof-strip alt text",
    )
    readme = replace_once(
        readme,
        r"## \d+ failures, \d+ patterns",
        f"## {failures} failures, {patterns} patterns",
        "README taxonomy heading",
    )
    readme_path.write_text(readme)

    index_path = ROOT / "docs" / "index.html"
    index = index_path.read_text()
    replacements = (
        (r"Explore \d+ use cases", f"Explore {cases} use cases", "explorer CTA count"),
        (r"<span><b>\d+</b><small>use cases</small></span>", f"<span><b>{cases}</b><small>use cases</small></span>", "explorer use-case proof"),
        (r"<span><b>\d+</b><small>industries</small></span>", f"<span><b>{industries}</b><small>industries</small></span>", "explorer industry proof"),
        (r"<span><b>\d+</b><small>model evals</small></span>", f"<span><b>{model_evals}</b><small>model evals</small></span>", "explorer model-eval proof"),
        (r"<span><b>\d+</b><small>observed failures</small></span>", f"<span><b>{failures}</b><small>observed failures</small></span>", "explorer failure proof"),
        (r"AAU-\d+", f"AAU-{cases:03d}", "explorer trace identifier"),
    )
    for pattern, replacement, label in replacements:
        index = replace_once(index, pattern, replacement, label)
    index_path.write_text(index)


def main() -> None:
    stats = repository_stats()
    OUTPUT.write_text(render(stats))
    STATS_LIGHT.write_text(render_stats(stats, dark=False))
    STATS_DARK.write_text(render_stats(stats, dark=True))
    sync_public_copy(stats)
    summary = ", ".join(f"{value} {label.lower()}" for label, value, _accent in stats)
    print(f"wrote dynamic hero, proof strips, and public counts — {summary}")


if __name__ == "__main__":
    main()
