#!/usr/bin/env python3
"""Build the browser-local Federal Pilot Desk from canonical exchange artifacts."""

from __future__ import annotations

import importlib.util
import json
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KIT = ROOT / "federal-pilot-kit"
DOCS = ROOT / "docs"
OUTPUT = DOCS / "federal-pilot-data.json"
ASSET = DOCS / "assets" / "federal-pilot.svg"
LESSON_ASSET = DOCS / "assets" / "lessons-exchange.svg"
SCHEMA_OUTPUTS = {
    "agency-intake.schema.json": DOCS / "federal-pilot-agency.schema.json",
    "vendor-evidence-response.schema.json": DOCS / "federal-pilot-vendor.schema.json",
    "acceptance-test-manifest.schema.json": DOCS / "federal-pilot-tests.schema.json",
    "lesson-record.schema.json": DOCS / "federal-ai-lesson.schema.json",
}


def load_module():
    spec = importlib.util.spec_from_file_location("aau_pilot", KIT / "aau_pilot.py")
    if not spec or not spec.loader:
        raise RuntimeError("cannot load federal-pilot-kit/aau_pilot.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render_svg(pilots: int, requirements: int, cases: int, visible_gaps: int) -> str:
    return f'''<!-- Generated by docs/make_federal_pilot_data.py -->
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="560" viewBox="0 0 1280 560" role="img" aria-labelledby="title desc">
  <title id="title">AAU Federal Pilot Kit</title>
  <desc id="desc">A forkable agency, responder, and reviewer evidence exchange with public synthetic pilots, exact tests, visible gaps, and protected human authority.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#071112"/><stop offset=".52" stop-color="#0a2523"/><stop offset="1" stop-color="#08151c"/></linearGradient>
    <linearGradient id="line" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#39e6ad"/><stop offset=".52" stop-color="#ffd166"/><stop offset="1" stop-color="#7ebcff"/></linearGradient>
    <pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#8fffe0" stroke-opacity=".055"/></pattern>
    <filter id="glow"><feGaussianBlur stdDeviation="7" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
    <style>text{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}}.sans{{font-family:system-ui,-apple-system,Segoe UI,sans-serif}}.k{{font-size:12px;font-weight:800;letter-spacing:2px}}.h{{font-size:42px;font-weight:850;letter-spacing:-1.8px}}.sub{{font-size:16px;fill:#b8cfca}}.node{{font-size:11px;font-weight:900;letter-spacing:1px}}.num{{font-size:28px;font-weight:900}}.label{{font-size:10px;font-weight:800;letter-spacing:1px}}</style>
  </defs>
  <rect width="1280" height="560" rx="25" fill="url(#bg)"/><rect width="1280" height="560" rx="25" fill="url(#grid)"/>
  <path d="M0 3H1280" stroke="url(#line)" stroke-width="6"/>
  <text x="58" y="59" class="k" fill="#66efc0">AAU / FEDERAL PILOT KIT 0.4 / PILOT · CLOSEOUT · LEARN · REVALIDATE</text>
  <text x="58" y="119" class="h sans" fill="#f4fff9">Claims enter.</text><text x="58" y="168" class="h sans" fill="#ffd166">Gaps stay visible.</text>
  <text x="58" y="205" class="sub sans">One open handoff for agency outcomes, responder evidence, exact tests, and accountable review.</text>
  <g transform="translate(876 36)"><path d="M48 80h230v128H48z" fill="#071b1b" stroke="#39e6ad" stroke-width="2"/><path d="M72 109h92M72 134h164M72 159h130" stroke="#7bdabe" stroke-width="7" stroke-linecap="round" opacity=".62"/><path d="M197 91l67 67-67 67" fill="#0b2527" stroke="#ffd166" stroke-width="3" filter="url(#glow)"/><path d="M213 155l15 15 28-35" fill="none" stroke="#ffd166" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><text x="163" y="248" text-anchor="middle" class="k" fill="#7ebcff">NON-RANKING / LOCAL / INSPECTABLE</text></g>
  <path d="M82 330H1195" stroke="#285953" stroke-width="3"/><path d="M82 330H1125" stroke="url(#line)" stroke-width="6" stroke-linecap="round"/>
  <g class="node" text-anchor="middle">
    <g transform="translate(100 330)"><circle r="25" fill="#39e6ad"/><text y="4" fill="#071814">01</text><text y="61" fill="#69edc4">AGENCY</text></g>
    <g transform="translate(370 330)"><circle r="25" fill="#70dfbb"/><text y="4" fill="#071814">02</text><text y="61" fill="#8de8cd">RESPONDER</text></g>
    <g transform="translate(640 330)"><circle r="25" fill="#ffd166"/><text y="4" fill="#15130a">03</text><text y="61" fill="#ffd166">EXACT TEST</text></g>
    <g transform="translate(910 330)"><circle r="25" fill="#91c5ff"/><text y="4" fill="#07111c">04</text><text y="61" fill="#91c5ff">REVIEWER</text></g>
    <g transform="translate(1180 330)"><circle r="25" fill="#7ebcff"/><text y="4" fill="#07111c">05</text><text y="61" fill="#7ebcff">HUMAN</text></g>
  </g>
  <g transform="translate(58 436)"><rect width="1164" height="82" rx="13" fill="#041314" stroke="#2b5b55"/>
    <g text-anchor="middle"><text x="145" y="37" class="num" fill="#39e6ad">{pilots}</text><text x="145" y="61" class="label" fill="#9dbbb5">REFERENCE PILOTS</text>
    <text x="436" y="37" class="num" fill="#ffd166">{requirements}</text><text x="436" y="61" class="label" fill="#9dbbb5">MEASURABLE GATES</text>
    <text x="727" y="37" class="num" fill="#7ebcff">{cases}</text><text x="727" y="61" class="label" fill="#9dbbb5">SYNTHETIC CASES</text>
    <text x="1018" y="37" class="num" fill="#ff8c7e">{visible_gaps}</text><text x="1018" y="61" class="label" fill="#9dbbb5">VISIBLE GAPS</text></g></g>
</svg>'''


def render_lessons_svg(lessons: int, stopped: int, dependencies: int, practices: int) -> str:
    return f'''<!-- Generated by docs/make_federal_pilot_data.py -->
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="560" viewBox="0 0 1280 560" role="img" aria-labelledby="title desc">
  <title id="title">AAU Federal AI Lessons Exchange</title>
  <desc id="desc">An evidence-linked public memory for changed, successful, and stopped synthetic AI pilots.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#12091f"/><stop offset=".52" stop-color="#1d1230"/><stop offset="1" stop-color="#081b22"/></linearGradient>
    <linearGradient id="signal" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#ff7a90"/><stop offset=".5" stop-color="#ffd166"/><stop offset="1" stop-color="#39e6ad"/></linearGradient>
    <pattern id="grid" width="34" height="34" patternUnits="userSpaceOnUse"><path d="M34 0H0V34" fill="none" stroke="#d8b5ff" stroke-opacity=".055"/></pattern>
    <filter id="glow"><feGaussianBlur stdDeviation="7" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
    <style>text{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}}.sans{{font-family:system-ui,-apple-system,Segoe UI,sans-serif}}.k{{font-size:12px;font-weight:850;letter-spacing:2px}}.h{{font-size:43px;font-weight:900;letter-spacing:-1.8px}}.sub{{font-size:16px;fill:#cbbbd8}}.node{{font-size:11px;font-weight:900;letter-spacing:1px}}.num{{font-size:28px;font-weight:950}}.label{{font-size:10px;font-weight:850;letter-spacing:1px}}</style>
  </defs>
  <rect width="1280" height="560" rx="25" fill="url(#bg)"/><rect width="1280" height="560" rx="25" fill="url(#grid)"/>
  <path d="M0 3H1280" stroke="url(#signal)" stroke-width="6"/>
  <text x="58" y="59" class="k" fill="#d8b5ff">AAU / FEDERAL AI LESSONS EXCHANGE 0.4 / PUBLIC MEMORY WITHOUT VENDOR RANKING</text>
  <text x="58" y="119" class="h sans" fill="#fff7ff">A pilot ends.</text><text x="58" y="168" class="h sans" fill="#ffd166">The lesson travels.</text>
  <text x="58" y="205" class="sub sans">Evidence → human decision → bounded practice → dated revalidation. Stopped pilots belong here too.</text>
  <g transform="translate(900 48)"><circle cx="120" cy="102" r="94" fill="#160c27" stroke="#d8b5ff" stroke-width="2"/><circle cx="120" cy="102" r="65" fill="none" stroke="#7ebcff" stroke-dasharray="5 8"/><path d="M75 112l27 27 63-73" fill="none" stroke="#39e6ad" stroke-width="11" stroke-linecap="round" stroke-linejoin="round" filter="url(#glow)"/><path d="M52 28l18 18M188 28l-18 18M52 176l18-18M188 176l-18-18" stroke="#ff7a90" stroke-width="5"/><text x="120" y="226" text-anchor="middle" class="k" fill="#ff9bab">SUCCESS · CHANGE · STOP</text></g>
  <path d="M83 329H1192" stroke="#4d365f" stroke-width="3"/><path d="M83 329H1118" stroke="url(#signal)" stroke-width="6" stroke-linecap="round"/>
  <g class="node" text-anchor="middle">
    <g transform="translate(108 329)"><circle r="25" fill="#ff7a90"/><text y="4" fill="#240612">01</text><text y="61" fill="#ff9bab">OBSERVE</text></g>
    <g transform="translate(378 329)"><circle r="25" fill="#c894ff"/><text y="4" fill="#160923">02</text><text y="61" fill="#d8b5ff">LINK</text></g>
    <g transform="translate(648 329)"><circle r="25" fill="#ffd166"/><text y="4" fill="#1a1200">03</text><text y="61" fill="#ffd166">BOUND</text></g>
    <g transform="translate(918 329)"><circle r="25" fill="#7ebcff"/><text y="4" fill="#07111c">04</text><text y="61" fill="#9dccff">VERIFY</text></g>
    <g transform="translate(1174 329)"><circle r="25" fill="#39e6ad"/><text y="4" fill="#071814">05</text><text y="61" fill="#65efc2">REUSE</text></g>
  </g>
  <g transform="translate(58 436)"><rect width="1164" height="82" rx="13" fill="#0b0814" stroke="#614a73"/>
    <g text-anchor="middle"><text x="145" y="37" class="num" fill="#d8b5ff">{lessons}</text><text x="145" y="61" class="label" fill="#ad9abb">PUBLIC LESSONS</text>
    <text x="436" y="37" class="num" fill="#ff7a90">{stopped}</text><text x="436" y="61" class="label" fill="#ad9abb">STOPPED PILOT</text>
    <text x="727" y="37" class="num" fill="#7ebcff">{dependencies}</text><text x="727" y="61" class="label" fill="#ad9abb">POLICY LINKS</text>
    <text x="1018" y="37" class="num" fill="#39e6ad">{practices}</text><text x="1018" y="61" class="label" fill="#ad9abb">BOUNDED PRACTICES</text></g></g>
</svg>'''


def main() -> None:
    module = load_module()
    examples = []
    requirement_count = 0
    case_count = 0
    visible_gaps = 0
    for directory in sorted((KIT / "examples").iterdir()):
        agency = json.loads((directory / "agency-intake.json").read_text())
        vendor = json.loads((directory / "vendor-response.json").read_text())
        tests = json.loads((directory / "acceptance-tests.json").read_text())
        assessment = module.assess_exchange(agency, vendor, tests)
        examples.append(
            {
                "slug": directory.name,
                "agency": agency,
                "vendor": vendor,
                "tests": tests,
                "assessment": assessment,
                "paths": {
                    "agency": f"federal-pilot-kit/examples/{directory.name}/agency-intake.json",
                    "vendor": f"federal-pilot-kit/examples/{directory.name}/vendor-response.json",
                    "tests": f"federal-pilot-kit/examples/{directory.name}/acceptance-tests.json",
                },
            }
        )
        requirement_count += assessment["summary"]["requirements"]
        case_count += assessment["summary"]["cases"]
        visible_gaps += assessment["summary"]["visible_gaps"]
    review_prompts = json.loads((KIT / "acquisition-review-prompts.json").read_text())
    source_ledger = json.loads((KIT / "lessons" / "source-ledger.json").read_text())
    source_errors = module.validate_source_ledger(source_ledger)
    if source_errors:
        raise ValueError("invalid lesson source ledger: " + "; ".join(source_errors))
    as_of = date.fromisoformat(max(item["last_verified"] for item in source_ledger["sources"]))
    lessons = []
    for path in sorted((KIT / "lessons" / "examples").glob("*.json")):
        lesson = json.loads(path.read_text())
        errors = module.validate_lesson(lesson)
        scan = module.scan_sensitive(lesson)
        if errors or not scan["safe_to_package"]:
            raise ValueError(f"invalid public lesson {path.name}: {errors or scan['findings']}")
        lessons.append(
            {
                "slug": path.stem,
                "path": f"federal-pilot-kit/lessons/examples/{path.name}",
                "record": lesson,
                "scan": scan,
                "drift": module.policy_drift_report(lesson, source_ledger, as_of),
            }
        )
    lesson_stats = {
        "lessons": len(lessons),
        "stopped": sum(item["record"]["outcome"]["result"] == "stopped" for item in lessons),
        "changed": sum(item["record"]["outcome"]["result"] == "changed" for item in lessons),
        "policy_dependencies": sum(len(item["record"]["policy_dependencies"]) for item in lessons),
        "bounded_practices": len({item["record"]["reusable_practice"]["title"] for item in lessons}),
        "scan_findings": sum(item["scan"]["finding_count"] for item in lessons),
    }
    output = {
        "version": "aau-federal-pilot-desk/0.4",
        "privacy": "Files stay in this browser tab. The Pilot Desk does not upload, persist, or transmit them.",
        "boundary": "No vendor ranking, award recommendation, certification, compliance finding, or government approval is produced.",
        "schema_paths": {
            "agency": "federal-pilot-agency.schema.json",
            "vendor": "federal-pilot-vendor.schema.json",
            "tests": "federal-pilot-tests.schema.json",
            "lesson": "federal-ai-lesson.schema.json",
        },
        "pack_files": list(module.PACK_NAMES),
        "review_prompts": review_prompts,
        "examples": examples,
        "lesson_exchange": {
            "version": module.LESSON_VERSION,
            "privacy": "Canonical examples are public synthetic records. Local filtering does not upload or persist data.",
            "boundary": "Lessons are not vendor rankings, award recommendations, contract clauses, certifications, disclosure decisions, or government approval.",
            "as_of": as_of.isoformat(),
            "stats": lesson_stats,
            "taxonomy": {
                "results": sorted(module.LESSON_RESULTS),
                "lifecycle_stages": sorted(module.LIFECYCLE_STAGES),
                "challenge_categories": sorted(module.CHALLENGE_CATEGORIES),
                "reuse_states": sorted(module.REUSE_STATES),
            },
            "source_ledger": source_ledger,
            "lessons": lessons,
        },
    }
    OUTPUT.write_text(json.dumps(output, indent=2) + "\n")
    for source, destination in SCHEMA_OUTPUTS.items():
        destination.write_text((KIT / source).read_text())
    ASSET.write_text(
        render_svg(len(examples), requirement_count, case_count, visible_gaps)
    )
    LESSON_ASSET.write_text(
        render_lessons_svg(
            lesson_stats["lessons"],
            lesson_stats["stopped"],
            lesson_stats["policy_dependencies"],
            lesson_stats["bounded_practices"],
        )
    )
    print(
        "wrote Federal Pilot Desk data — "
        f"{len(examples)} pilots, {requirement_count} gates, {case_count} cases, "
        f"{visible_gaps} visible gaps, {lesson_stats['lessons']} public lessons"
    )


if __name__ == "__main__":
    main()
