"""Generate the landing-page hero with proof points derived from repository data.

The detailed backdrop is intentionally static artwork. The proof strip is SVG text
generated from source-of-truth files, so adding a use case or evaluation never
requires opening an image editor:

    python docs/make_hero.py
"""

from __future__ import annotations

import base64
import json
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"
CATALOG = ROOT / "docs" / "use-cases.json"
TAXONOMY = ASSETS / "taxonomy.json"
BACKDROP = ASSETS / "hero-v4.webp"
OUTPUT = ASSETS / "hero.svg"


def repository_stats() -> tuple[tuple[str, int, str], ...]:
    """Return label, value, and accent for every public proof point."""
    cases = json.loads(CATALOG.read_text())
    taxonomy = json.loads(TAXONOMY.read_text())
    model_evals = sum(
        json.loads(path.read_text()).get("backend") != "mock"
        for path in ROOT.glob("*/*/results/eval_*.json")
    )
    return (
        ("VERIFIED USE CASES", len(cases), "#1687ff"),
        ("INDUSTRIES", len({item["industry"] for item in cases}), "#23d65b"),
        ("MODEL EVALS", model_evals, "#a865ff"),
        ("OBSERVED FAILURES", taxonomy["failure_modes"], "#ff4938"),
    )


def render(stats: tuple[tuple[str, int, str], ...]) -> str:
    encoded_backdrop = base64.b64encode(BACKDROP.read_bytes()).decode("ascii")
    proof = " · ".join(f"{value} {label.lower()}" for label, value, _accent in stats)
    columns: list[str] = []
    start_x, column_width = 88, 168
    for index, (label, value, accent) in enumerate(stats):
        x = start_x + index * column_width
        if index:
            columns.append(
                f'<path d="M {x - 18} 804 V 861" stroke="#31363e" stroke-width="1"/>'
            )
        columns.extend(
            (
                f'<circle cx="{x}" cy="816" r="4" fill="{accent}"/>',
                f'<text x="{x + 14}" y="828" class="proof-value" fill="#f5f7fa">{value}</text>',
                f'<text x="{x}" y="856" class="proof-label" fill="{accent}">{escape(label)}</text>',
            )
        )

    return f'''<!-- Generated by docs/make_hero.py; edit the data, not the numbers. -->
<svg xmlns="http://www.w3.org/2000/svg" width="1672" height="941" viewBox="0 0 1672 941" role="img" aria-labelledby="hero-title hero-description">
  <title id="hero-title">Awesome Agentic Use Cases — verified, not just runnable</title>
  <desc id="hero-description">Evidence paths through tools, policy gates, uncertainty, and failures. Repository proof points: {escape(proof)}.</desc>
  <defs>
    <linearGradient id="proof-surface" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#050607"/>
      <stop offset="0.7" stop-color="#080a0d"/>
      <stop offset="1" stop-color="#080a0d" stop-opacity="0.96"/>
    </linearGradient>
    <filter id="proof-glow" x="-20%" y="-50%" width="140%" height="200%">
      <feGaussianBlur stdDeviation="7"/>
    </filter>
    <style>
      text {{ font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace; }}
      .proof-value {{ font-size: 34px; font-weight: 750; letter-spacing: -1px; }}
      .proof-label {{ font-size: 12px; font-weight: 700; letter-spacing: 1.25px; }}
    </style>
  </defs>
  <image width="1672" height="941" href="data:image/webp;base64,{encoded_backdrop}"/>
  <rect x="68" y="783" width="704" height="96" rx="8" fill="#050607" opacity="0.96" filter="url(#proof-glow)"/>
  <rect x="68" y="783" width="704" height="96" rx="8" fill="url(#proof-surface)" stroke="#29303a"/>
  <path d="M 69 784 H 771" stroke="#1687ff" stroke-width="2" opacity="0.75"/>
  {''.join(columns)}
</svg>
'''


def main() -> None:
    stats = repository_stats()
    OUTPUT.write_text(render(stats))
    summary = ", ".join(f"{value} {label.lower()}" for label, value, _accent in stats)
    print(f"wrote {OUTPUT.relative_to(ROOT)} — {summary}")


if __name__ == "__main__":
    main()
